apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: cf
  name: replicaset-reporter
  namespace: eks-moran
spec:
  eventBusName: codefresh-eventbus
  resource:
    replicasets:
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
      filter:
        createdBy: null
      group: apps
      namespace: eks-moran
      resource: replicasets
      version: v1
  template:
    serviceAccountName: replicaset-reporter-sa
status: {}
